#!/bin/python

import struct

MAGIC      = b"cIMG"
VERSION    = 1
WIDTH      = 25
HEIGHT     = 11

with open("example.cimg", "wb") as output:
    output.write(MAGIC)
    output.write(VERSION.to_bytes(4, "little"))
    output.write(WIDTH.to_bytes(2, "little"))
    output.write(HEIGHT.to_bytes(4, "little"))
    output.write(b"A" * (WIDTH * HEIGHT))
